### ISSUE TITLE
Automatically set ports for services

### ISSUE THREAD

**Issue by sushant21** [devclub-iitd/DeployBot#11]
Currently ports in docker-compose.yml are set manually, leading to possible conflicts across services. One option is to list occupied ports somewhere, and user must make sure to exclude these. 
More user-friendly is to treat ports listed in docker-compose as 'virtual' , and deploybot must map them to available ports of the server.  Pros/cons?

**Comment by arpit-saxena** [comment]
The solution to this is to have the user only specify the port to publish in `docker-compose.yml` and not the target machine port to map it to.

So instead of having
```yaml
ports:
      - '${PORT}:${PORT}'
```

They would have
```yaml
ports:
      - '${PORT}'
```

This way, docker will automatically map it with an available port on the machine.
