### ISSUE TITLE
Re-deploying a service

### ISSUE THREAD

**Issue by sushant21** [devclub-iitd/DeployBot#12]
If re-deploying a service, the slack interface should give some hint on which server the service is already running?

**Comment by Atishya-jain** [comment]
Currently @Divi09112 had changed the system to include stop service.

So we cannot redeploy until a particular service is down.
Does it matter now on which VM was the service earlier deployed?

**Comment by imperfect-fourth** [comment]
@Atishya-jain If a service is using a persistent database then we would want to run that service on the same server because the db container won't be accessible from other VMs unless it is run as a different service.

**Comment by imperfect-fourth** [comment]
Closing this issue. Redeploy added in #25 .
