### ISSUE TITLE
Prune old docker images to save space

### ISSUE THREAD

**Issue by imperfect-fourth** [devclub-iitd/DeployBot#14]
Remove old versions of docker images when deploying a service.

**Comment by aagrxyz** [comment]
We also, need to add a controller that runs a script to remove old docker images from the system.

Something like `docker image prune -a` should work fine for our use case. But, this needs to be run on every VM. Probably we can run it within our container by faking docker endpoint using docker-machine.

**Comment by imperfect-fourth** [comment]
Closed by #41
