### ISSUE TITLE
DeployBot is not really thread safe

### ISSUE THREAD

**Issue by aagrxyz** [devclub-iitd/DeployBot#30]
We get state from history, do some checking/validation and  set the state as deploying. 

Two concurrent threads can read the state as stopped and then set the state to deploying and then there will be two concurrent deploy.sh scripts running. This is bad. We need a way of generating an e-tag of the state and make every caller get the state and then change it, while respecting e-tag values.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag

**Comment by arpit-saxena** [comment]
Why not just have the threads write the state as "deploying" to history before moving further (instead of just changing the thread local value as is happening now)? That way, after one thread releases the lock, the other thread won't be able to set the state as deploying.

**Comment by arpit-saxena** [comment]
How will that happen? After reading the state as stopped, each thread writes to history the state as deploying. Only one thread will succeed in writing the state, and the other will get an error as `history.SetState` will throw an error if the current status was deploying

**Comment by aagrxyz** [comment]
That is a pretty recent addition, and that does not check for these things. It was written to only check if a subdomain is present or not.

It can happen while stopping at this moment. Two threads read the state as running, both of them set as stopping. Both will suceed and then call the stop.sh to stop which will have again race conditions.

The best way to handle such changes is an E-tag sincw we cannot make our changes atomic.

**Comment by arpit-saxena** [comment]
Right, that makes sense. So the E-Tag will basically allow us to implement a atomic CompareAndSwap operation in the `SetState` function.

**Comment by aagrxyz** [comment]
Yes. Exactly. Will you be willing to implement it? I can review it,

**Comment by arpit-saxena** [comment]
Yeah, sure, I'll implement it.

**Comment by aagrxyz** [comment]
Why did you close the PR?

Also, you can take a hash of the timestamp and the repoURL (probably some unexported secret too) and return an E-TAG instead of passing around the whole state everytime you need to change.

**Comment by arpit-saxena** [comment]
I figured what I was doing wasn't the best, so I closed it to make some changes. Didn't get time to work on it after that.
Yeah ok, I'll do that. I'll also take a secret from the .env file for the moment.
